export default {
  ADD_MESSAGE_NOTIFICATION: 'ADD_MESSAGE_NOTIFICATION',
  REMOVE_MESSAGE_NOTIFICATION: 'REMOVE_MESSAGE_NOTIFICATION',
  REMOVE_MESSAGES_NOTIFICATION: 'REMOVE_MESSAGES_NOTIFICATION',
  FETCH_UNREAD_MESSAGES_START: 'FETCH_UNREAD_MESSAGES_START',
  FETCH_UNREAD_MESSAGES_SUCCESS: 'FETCH_UNREAD_MESSAGES_SUCCESS',
  FETCH_UNREAD_MESSAGES_FAILURE: 'FETCH_UNREAD_MESSAGES_FAILURE'
};
