export default {
  ADD_MESSAGE_NOTIFICATION: 'ADD_MESSAGE_NOTIFICATION',
  REMOVE_MESSAGE_NOTIFICATION: 'REMOVE_MESSAGE_NOTIFICATION',
  REMOVE_MESSAGES_NOTIFICATION: 'REMOVE_MESSAGES_NOTIFICATION',
  FETCH_UNREAD_MESSAGES_START: 'FETCH_UNREAD_MESSAGES_START',
  FETCH_UNREAD_MESSAGES_SUCCESS: 'FETCH_UNREAD_MESSAGES_SUCCESS',
  FETCH_UNREAD_MESSAGES_FAILURE: 'FETCH_UNREAD_MESSAGES_FAILURE',
  SET_ONLINE_USERS: 'SET_ONLINE_USERS',
  SET_VIDEO_CALL_NOTIFICATION: 'SET_VIDEO_CALL_NOTIFICATION',
  RESET_VIDEO_CALL_NOTIFICATION: 'RESET_VIDEO_CALL_NOTIFICATION'
};
