export default {
  ADD_MESSAGE_NOTIFICATION: 'ADD_MESSAGE_NOTIFICATION',
  REMOVE_MESSAGE_NOTIFICATION: 'REMOVE_MESSAGE_NOTIFICATION',
  REMOVE_MESSAGES_NOTIFICATION: 'REMOVE_MESSAGES_NOTIFICATION'
};
